# Generated by Django 5.0.4 on 2024-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_prompt", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
            ],
        ),
    ]
