# Generated by Django 5.0.4 on 2024-04-26 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_image_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 4, 26, 16, 36, 15, 152364, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
